@startuml Diagramme_Classe_StoreManagerPro

    class Role {
        - id
        - nom
    }

    class Utilisateur {
        - id
        - nomComplet
        - email
        - mot_passe
    }



    class Produit {
        - id
        - libelle
        - prixVente
        - stock
        - seuil
    }

    class Client {
        - id
        - nom
        - prenom
        - email
        - tel
        - limiteCredit
    }

    class Fournisseur {
        - id
        - nomComplet
        - email
        - tel
    }



    class Commande {
        - id
        - datCommande
        - montantInitial
        - avance
        - estCredit
    }

    class LigneCommande {
        - id
        - quantite
        - prixUnitaire
    }

    class ModePaiement {
        - id
        - libelle
    }

    class Reglement {
        - id
        - dateReglement
        - montant
    }

    class Dette {
        - id
        - montantInitial
        - montantRestant
        - statut
        - dateEcheance
    }



    class StatutAppro {
        - id
        - nom
    }

    class Appro {
        - id
        - refBl
        - dateAppro
        - montantTotal
    }

    class LigneAppro {
        - id
        - qteAppro
        - qteRecu
        - prixReel
    }




Utilisateur "0..*" --> "1" Role : posseder

Client "1" --> "0..*" Commande : passer
Commande "1" --> "1..*" LigneCommande : composer
Produit "1" --> "0..*" LigneCommande : figurer dans
Commande "0..*" --> "1" ModePaiement : regler via
Commande "0..*" --> "1" Utilisateur : enregistree par

Commande "1" --> "0..1" Dette : engendrer
Dette "1" --> "0..*" Reglement : faire l'objet de
Reglement "0..*" --> "1" ModePaiement : effectue par
Reglement "0..*" --> "1" Utilisateur : encaisse par

Appro "0..*" --> "1" Fournisseur : provenir de
Appro "1" --> "1..*" LigneAppro : contenir
Produit "1" --> "0..*" LigneAppro : concerne par
StatutAppro "1" --> "0..*" Appro : qualifier
Appro "0..*" --> "1" Utilisateur : receptionne par

@enduml